version: '2'
services:
    sponge_forge:
        image: openco/sponge-forge
        container_name: forge
        environment:
            - "MINECRAFT_PORT:25566"
            - "MINECRAFT_EULA:true"
            - "MINECRAFT_MAXHEAP:1024M"
            - "FORGE_VERSION:1.12.2-14.23.5.2855"
            - "SPONGE_VERSION:1.12.2-2838-7.3.0"
        expose:
            - "25565"
        ports:
            - "25566:25566"
        stdin_open: true
        tty: true
        volumes:
            - ./data:/forge:rw
